
-- audyty
USE master;
CREATE SERVER AUDIT AudytLoginy
TO FILE
(
	FILEPATH = 'C:\SQLAudyt\BledneLoginy',
	MAXSIZE = 10 MB,
	MAX_FILES = 10,
	RESERVE_DISK_SPACE = ON
);


ALTER SERVER AUDIT AudytLoginy WITH (STATE = ON);

-- audyt na bledne loginy
CREATE SERVER AUDIT SPECIFICATION AudytBledneLoginy
FOR SERVER AUDIT AudytLoginy
ADD (FAILED_LOGIN_GROUP);

ALTER SERVER AUDIT SPECIFICATION AudytBledneLoginy WITH (STATE = ON);


-- audyt uprawnienia
CREATE SERVER AUDIT AudytUprawnienia
TO FILE
(
	FILEPATH = 'C:\SQLAudyt\Uprawnienia',
	MAXSIZE = 10 MB,
	MAX_FILES = 10,
	RESERVE_DISK_SPACE = ON
);

-- audyt na zmiany uprawnien
CREATE SERVER AUDIT SPECIFICATION AudytZmianyUprawnien
FOR SERVER AUDIT AudytUprawnienia
ADD (SERVER_ROLE_MEMBER_CHANGE_GROUP),
ADD (DATABASE_ROLE_MEMBER_CHANGE_GROUP),
ADD (SERVER_PERMISSION_CHANGE_GROUP);

ALTER SERVER AUDIT SPECIFICATION AudytZmianyUprawnien WITH (STATE = ON);

-- audyty na poziomie bazy danych
CREATE SERVER AUDIT AudytBaza
TO FILE
(
	FILEPATH = 'C:\SQLAudyt\Baza',
	MAXSIZE = 10 MB,
	MAX_FILES = 10,
	RESERVE_DISK_SPACE = ON
);

-- audyty bazy danych

USE LekarzKardiolog;
GO


CREATE DATABASE AUDIT SPECIFICATION AudytZmiany
FOR SERVER AUDIT AudytBaza
ADD (SCHEMA_OBJECT_CHANGE_GROUP), 
ADD (SELECT, INSERT, UPDATE, DELETE ON DATABASE::[LekarzKardiolog] BY [public]);

ALTER DATABASE AUDIT SPECIFICATION AudytZmiany WITH (STATE = ON);
GO